version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=hydroponic_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=hydroponic_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    depends_on:
      - db

volumes: # Volume definition outside the services section
  postgres_data:  # Volume name